##################################################################################################
# Productpage service
##################################################################################################
apiVersion: v1
kind: Service
metadata:
  name: productpage
  labels:
    app: productpage
    service: productpage
spec:
  ports:
  - port: 9080
    name: http
  selector:
    app: productpage
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: productpage-v1
  labels:
    app: productpage
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ratings
      version: v1
  template:
    metadata:
      labels:
        app: productpage
        version: v1
    spec:
      containers:
      - name: productpage
        image: sergiocalderon/productpage:v1
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 9080
        securityContext:
          runAsUser: 1000
---
##################################################################################################
# External IP
##################################################################################################
apiVersion: v1
kind: Service
metadata:
  name: productpage-external
  labels:
    app: productpage
    service: productpage
spec:
  ports:
  - port: 9080
    targetPort: 9080
    nodePort: 30000 #Puerto a poner en el browser (valor entre 300000 y 32767)
    name: http
  selector:
    app: productpage
  type: LoadBalancer #Asigna una IP externa
---

